name: Node Express GraphQL Template CI

on:
  pull_request:
    branches: [develop]

jobs:
  build_and_test:
    name: Build & Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Update diagram
        uses: githubocto/repo-visualizer@0.7.1
        with:
          should_push: true
          branch: ${{ github.ref }}
          output_file: "images/diagram.svg"
      # - name: Setup environment
      #   uses: actions/setup-node@v2
      #   with:
      #     cache: 'yarn'
      #     node-version: ${{ matrix.node-version }}
      # - name: Install dependencies
      #   run: yarn install
      # - name: Lint
      #   run: yarn lint
      # - name: Test
      #   run: yarn test
      # - name: Build
      #   run: yarn build:local
